const STORAGE_KEY = "bluenote-state";
const DB_NAME = "bluenote-audio";
const DB_VERSION = 1;
const state = loadState();
let currentPlaylistId = "library";
let currentTrackId = null;
let audioUrl = null;
let unlockKey = null;

const unlockConfig = { salt: "QEdkJNxWHoRnoQtGaq_ePg", iv: "L2EGjS6VkkxQ368z", data: "lViFJkhgjfN-5tzQoqcj4bZLCp_qim-KGzOPsGikvL-5" };

function decodeBase64Url(value) { const normalized = value.replace(/-/g, "+").replace(/_/g, "/"); return Uint8Array.from(atob(normalized.padEnd(Math.ceil(normalized.length / 4) * 4, "=")), (character) => character.charCodeAt(0)); }
async function deriveUnlockKey(passphrases) { const material = new TextEncoder().encode(passphrases.join("\n")); const imported = await crypto.subtle.importKey("raw", material, "PBKDF2", false, ["deriveKey"]); return crypto.subtle.deriveKey({ name: "PBKDF2", salt: decodeBase64Url(unlockConfig.salt), iterations: 250000, hash: "SHA-256" }, imported, { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]); }
async function verifyUnlock(passphrases) { const key = await deriveUnlockKey(passphrases); const decrypted = await crypto.subtle.decrypt({ name: "AES-GCM", iv: decodeBase64Url(unlockConfig.iv) }, key, decodeBase64Url(unlockConfig.data)); return new TextDecoder().decode(decrypted) === "BLUENOTE-UNLOCKED" ? key : null; }
async function encryptFile(file) { const iv = crypto.getRandomValues(new Uint8Array(12)); const data = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, unlockKey, await file.arrayBuffer()); return { data, iv: Array.from(iv), type: file.type, name: file.name }; }
async function decryptFile(record) { const data = await crypto.subtle.decrypt({ name: "AES-GCM", iv: new Uint8Array(record.iv) }, unlockKey, record.data); return new File([data], record.name, { type: record.type }); }

const elements = { audio: document.getElementById("audioPlayer"), songInput: document.getElementById("songInput"), songList: document.getElementById("songList"), playlistNav: document.getElementById("playlistNav"), playlistGrid: document.getElementById("playlistGrid"), publishedGrid: document.getElementById("publishedGrid"), archiveButton: document.getElementById("archiveButton"), archiveDialog: document.getElementById("archiveDialog"), closeArchiveButton: document.getElementById("closeArchiveButton"), exportPlaylistSelect: document.getElementById("exportPlaylistSelect"), exportIconInput: document.getElementById("exportIconInput"), exportButton: document.getElementById("exportPlaylistButton"), importArchiveInput: document.getElementById("importArchiveInput"), exportStatus: document.getElementById("exportStatus"), search: document.getElementById("searchInput"), trackListTitle: document.getElementById("trackListTitle"), play: document.getElementById("playButton"), currentTitle: document.getElementById("currentTitle"), currentMeta: document.getElementById("currentMeta"), progress: document.getElementById("progressInput"), currentTime: document.getElementById("currentTime"), duration: document.getElementById("duration"), volume: document.getElementById("volumeInput") };

function loadState() { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "null"); return saved || { tracks: [], playlists: [{ id: "library", name: "All tracks", trackIds: [], published: false }], published: [] }; }
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function makeId() { return `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function getTrack(trackId) { return state.tracks.find((track) => track.id === trackId); }
function getPlaylist(playlistId) { return state.playlists.find((playlist) => playlist.id === playlistId); }
function displayName(fileName) { return fileName.replace(/\.[^/.]+$/, "").replace(/[_-]+/g, " "); }
function formatTime(seconds) { if (!Number.isFinite(seconds)) return "0:00"; return `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`; }

function openDatabase() { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, DB_VERSION); request.onupgradeneeded = () => request.result.createObjectStore("tracks", { keyPath: "id" }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function storeFile(trackId, file) { const database = await openDatabase(); const encrypted = await encryptFile(file); return new Promise((resolve, reject) => { const request = database.transaction("tracks", "readwrite").objectStore("tracks").put({ id: trackId, encrypted }); request.onsuccess = resolve; request.onerror = () => reject(request.error); }); }
async function getFile(trackId) { const database = await openDatabase(); return new Promise((resolve, reject) => { const request = database.transaction("tracks", "readonly").objectStore("tracks").get(trackId); request.onsuccess = async () => { try { const record = request.result; resolve(record?.encrypted ? await decryptFile(record.encrypted) : record?.file || null); } catch (error) { reject(error); } }; request.onerror = () => reject(request.error); }); }

async function addSongs(files) { try { for (const file of files) { const track = { id: makeId(), name: displayName(file.name), fileName: file.name, addedAt: Date.now() }; await storeFile(track.id, file); state.tracks.push(track); state.playlists[0].trackIds.push(track.id); } saveState(); render(); } catch (error) { console.error("Could not add music:", error); alert("This MP3 could not be added. Please unlock the library again and retry."); } }
function render() { renderNav(); renderTracks(); renderPlaylists(); renderPublished(); renderExportOptions(); document.getElementById("trackCount").textContent = state.tracks.length; document.getElementById("playlistCount").textContent = state.playlists.length - 1; document.getElementById("libraryHint").textContent = state.tracks.length ? `${state.tracks.length} track${state.tracks.length === 1 ? "" : "s"} ready to play.` : "Add MP3 files to begin building your collection."; }
function selectLibrary() { currentPlaylistId = "library"; showView("library"); renderTracks(); }
function openPlaylist(playlistId) { currentPlaylistId = playlistId; showView("library"); renderTracks(); }
function renderNav() { elements.playlistNav.innerHTML = `<button class="playlist-nav-item" data-playlist="library">All tracks<span>${state.tracks.length}</span></button>${state.playlists.slice(1).map((playlist) => `<button class="playlist-nav-item" data-playlist="${playlist.id}">${escapeHtml(playlist.name)}<span>${playlist.trackIds.length}</span></button>`).join("")}`; elements.playlistNav.querySelectorAll("button").forEach((button) => button.addEventListener("click", () => button.dataset.playlist === "library" ? selectLibrary() : openPlaylist(button.dataset.playlist))); elements.playlistNav.querySelectorAll("button").forEach((button) => button.classList.toggle("active", button.dataset.playlist === currentPlaylistId)); }
function renderTracks() { const playlist = currentPlaylistId === "library" ? state.playlists[0] : getPlaylist(currentPlaylistId); const query = elements.search.value.toLowerCase(); const tracks = (playlist?.trackIds || []).map(getTrack).filter(Boolean).filter((track) => track.name.toLowerCase().includes(query)); elements.trackListTitle.textContent = playlist?.name || "All tracks"; elements.songList.innerHTML = tracks.length ? tracks.map((track, index) => `<div class="track-row ${track.id === currentTrackId ? "playing" : ""}"><span class="track-number">${String(index + 1).padStart(2, "0")}</span><button class="track-name" data-play="${track.id}"><span class="track-play-indicator">${track.id === currentTrackId ? "||" : ">"}</span>${escapeHtml(track.name)}</button><span class="track-file">${escapeHtml(track.fileName)}</span><button class="more-button" data-download="${track.id}" title="Download song">Download</button><button class="more-button" data-add="${track.id}" title="Add to playlist">Add</button><button class="more-button" data-delete="${track.id}" title="Remove track">Delete</button></div>`).join("") : `<div class="empty-state"><strong>${query ? "No matching tracks" : "Your library is ready for its first track"}</strong><span>${query ? "Try another search." : "Use Add music to store MP3 files in this browser."}</span></div>`; elements.songList.querySelectorAll("[data-play]").forEach((button) => button.addEventListener("click", () => playTrack(button.dataset.play))); elements.songList.querySelectorAll("[data-download]").forEach((button) => button.addEventListener("click", () => downloadTrack(button.dataset.download))); elements.songList.querySelectorAll("[data-add]").forEach((button) => button.addEventListener("click", () => addToPlaylist(button.dataset.add))); elements.songList.querySelectorAll("[data-delete]").forEach((button) => button.addEventListener("click", () => deleteTrack(button.dataset.delete))); }
function renderPlaylists() { elements.playlistGrid.innerHTML = state.playlists.slice(1).length ? state.playlists.slice(1).map((playlist) => { const artStyle = playlist.iconDataUrl ? ` style="background-image: url('${escapeHtml(playlist.iconDataUrl)}'); background-size: cover; background-position: center;"` : ""; return `<article class="playlist-card"><div class="playlist-art"${artStyle}><span>${playlist.trackIds.length}</span><small>tracks</small></div><div class="playlist-card-body"><div><h3>${escapeHtml(playlist.name)}</h3><p>${playlist.trackIds.length} tracks${playlist.published ? " · Published" : ""}</p></div><div class="playlist-actions"><button class="small-button" data-open-playlist="${playlist.id}">Open</button><button class="small-button" data-rename-playlist="${playlist.id}">Rename</button></div></div></article>`; }).join("") : `<div class="empty-state wide"><strong>No playlists yet</strong><span>Create one to start arranging your collection.</span></div>`; elements.playlistGrid.querySelectorAll("[data-open-playlist]").forEach((button) => button.addEventListener("click", () => openPlaylist(button.dataset.openPlaylist))); elements.playlistGrid.querySelectorAll("[data-rename-playlist]").forEach((button) => button.addEventListener("click", () => renamePlaylist(button.dataset.renamePlaylist))); }
function renderPublished() { elements.publishedGrid.innerHTML = state.published.length ? state.published.map((item) => `<article class="published-card"><span class="published-label">Published playlist</span><h3>${escapeHtml(item.name)}</h3><p>${item.trackCount} tracks · by ${escapeHtml(item.author)}</p><button class="small-button" data-play-published="${item.playlistId}">Play preview</button></article>`).join("") : `<div class="empty-state wide"><strong>Your discovery feed is quiet</strong><span>Publish a playlist to put your music on the stage.</span></div>`; elements.publishedGrid.querySelectorAll("[data-play-published]").forEach((button) => button.addEventListener("click", () => openPlaylist(button.dataset.playPublished))); }
function renderExportOptions() { const playlists = state.playlists.slice(1); elements.exportPlaylistSelect.innerHTML = playlists.length ? playlists.map((playlist) => `<option value="${playlist.id}">${escapeHtml(playlist.name)} (${playlist.trackIds.length} tracks)</option>`).join("") : "<option value=\"\">Create a playlist first</option>"; elements.exportButton.disabled = !playlists.length; }
function archiveName(name) { return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "playlist"; }
function fileExtension(fileName) { return fileName.split(".").pop().toLowerCase().replace(/[^a-z0-9]/g, "") || "jpg"; }
function fileAsDataUrl(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); }
async function exportPlaylistArchive() { const playlist = getPlaylist(elements.exportPlaylistSelect.value); if (!playlist || typeof JSZip === "undefined") return; elements.exportButton.disabled = true; elements.exportStatus.textContent = "Packaging tracks..."; try { const zip = new JSZip(); const manifest = { format: "AstolfoNote", version: 1, name: playlist.name, tracks: [] }; const trackFolder = zip.folder("tracks"); for (const [index, trackId] of playlist.trackIds.entries()) { const track = getTrack(trackId); const file = await getFile(trackId); if (!track || !file) continue; const fileName = `${String(index + 1).padStart(3, "0")}-${track.fileName.replace(/[^a-zA-Z0-9._-]/g, "_")}`; trackFolder.file(fileName, await file.arrayBuffer()); manifest.tracks.push({ file: `tracks/${fileName}`, title: track.name, originalName: track.fileName }); } const icon = elements.exportIconInput.files[0]; if (icon) { const iconName = `cover.${fileExtension(icon.name)}`; zip.file(iconName, await icon.arrayBuffer()); manifest.cover = iconName; } zip.file("manifest.json", JSON.stringify(manifest, null, 2)); const archive = await zip.generateAsync({ type: "blob", compression: "DEFLATE" }); const downloadUrl = URL.createObjectURL(archive); const link = document.createElement("a"); link.href = downloadUrl; link.download = `${archiveName(playlist.name)}.astfnote`; link.click(); URL.revokeObjectURL(downloadUrl); elements.exportStatus.textContent = `Exported ${manifest.tracks.length} track${manifest.tracks.length === 1 ? "" : "s"}.`; } catch (error) { console.error("Could not export playlist:", error); elements.exportStatus.textContent = "Export failed. Unlock the library again and retry."; } finally { elements.exportButton.disabled = !state.playlists.slice(1).length; } }
async function importPlaylistArchive(event) { const archiveFile = event.target.files[0]; if (!archiveFile || typeof JSZip === "undefined") return; elements.importArchiveInput.disabled = true; elements.exportStatus.textContent = "Opening AstolfoNote..."; try { if (!archiveFile.name.toLowerCase().endsWith(".astfnote")) throw new Error("Wrong file extension"); const zip = await JSZip.loadAsync(archiveFile); const manifestFile = zip.file("manifest.json"); if (!manifestFile) throw new Error("Missing manifest"); const manifest = JSON.parse(await manifestFile.async("text")); if (manifest.format !== "AstolfoNote" || !Array.isArray(manifest.tracks)) throw new Error("Invalid AstolfoNote"); const importedPlaylist = { id: makeId(), name: manifest.name || "Imported playlist", trackIds: [], published: false }; for (const item of manifest.tracks) { const entry = zip.file(item.file); if (!entry) throw new Error(`Missing track: ${item.file}`); const blob = await entry.async("blob"); const fileName = item.originalName || item.file.split("/").pop(); const file = new File([blob], fileName, { type: blob.type || "audio/mpeg" }); const track = { id: makeId(), name: item.title || displayName(fileName), fileName, addedAt: Date.now() }; await storeFile(track.id, file); state.tracks.push(track); importedPlaylist.trackIds.push(track.id); } if (manifest.cover) { const coverEntry = zip.file(manifest.cover); if (coverEntry) importedPlaylist.iconDataUrl = await fileAsDataUrl(new File([await coverEntry.async("blob")], manifest.cover)); } state.playlists.push(importedPlaylist); saveState(); render(); elements.exportStatus.textContent = `Imported ${importedPlaylist.trackIds.length} track${importedPlaylist.trackIds.length === 1 ? "" : "s"}.`; } catch (error) { console.error("Could not import AstolfoNote:", error); elements.exportStatus.textContent = error.message === "Wrong file extension" ? "Only .astfnote files can be imported." : "Import failed. Check that this is a valid AstolfoNote file."; } finally { elements.importArchiveInput.disabled = false; event.target.value = ""; } }

async function playTrack(trackId) { const track = getTrack(trackId); if (!track) return; const file = await getFile(trackId); if (!file) return; if (audioUrl) URL.revokeObjectURL(audioUrl); audioUrl = URL.createObjectURL(file); elements.audio.src = audioUrl; currentTrackId = trackId; elements.currentTitle.textContent = track.name; elements.currentMeta.textContent = track.fileName; document.getElementById("nowPlayingStat").textContent = track.name; await elements.audio.play(); renderTracks(); updatePlayButton(); }
function trackSequence() { const playlist = currentPlaylistId === "library" ? state.playlists[0] : getPlaylist(currentPlaylistId); return playlist?.trackIds || []; }
function moveTrack(direction) { const sequence = trackSequence(); if (!sequence.length) return; const index = Math.max(0, sequence.indexOf(currentTrackId)); const nextIndex = (index + direction + sequence.length) % sequence.length; playTrack(sequence[nextIndex]); }
async function downloadTrack(trackId) { const track = getTrack(trackId); const file = await getFile(trackId); if (!track || !file) return; const downloadUrl = URL.createObjectURL(file); const link = document.createElement("a"); link.href = downloadUrl; link.download = track.fileName; link.click(); URL.revokeObjectURL(downloadUrl); }
function updatePlayButton() { elements.play.textContent = elements.audio.paused ? "Play" : "Pause"; }
function deleteTrack(trackId) { state.tracks = state.tracks.filter((track) => track.id !== trackId); state.playlists.forEach((playlist) => { playlist.trackIds = playlist.trackIds.filter((id) => id !== trackId); }); if (currentTrackId === trackId) { elements.audio.pause(); currentTrackId = null; } saveState(); render(); }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]); }
function addToPlaylist(trackId) { const playlists = state.playlists.slice(1); if (!playlists.length) { alert("Create a playlist first."); return; } const choice = prompt(`Type the number of the playlist to add this track to:\n${playlists.map((playlist, index) => `${index + 1}. ${playlist.name}`).join("\n")}`); const playlist = playlists[Number(choice) - 1]; if (!playlist || playlist.trackIds.includes(trackId)) return; playlist.trackIds.push(trackId); saveState(); render(); }
function createPlaylist() { const name = prompt("Name your playlist:", "New playlist"); if (!name?.trim()) return; state.playlists.push({ id: makeId(), name: name.trim(), trackIds: [], published: false }); saveState(); render(); }
function renamePlaylist(playlistId) { const playlist = getPlaylist(playlistId); const name = prompt("Rename playlist:", playlist?.name || ""); if (playlist && name?.trim()) { playlist.name = name.trim(); saveState(); render(); } }
function publishPlaylist() { const playlists = state.playlists.slice(1); if (!playlists.length) { alert("Create a playlist before publishing it."); return; } const choice = prompt(`Type the number of the playlist to publish:\n${playlists.map((playlist, index) => `${index + 1}. ${playlist.name}`).join("\n")}`); const playlist = playlists[Number(choice) - 1]; if (!playlist) return; playlist.published = true; state.published = state.published.filter((item) => item.playlistId !== playlist.id); state.published.push({ playlistId: playlist.id, name: playlist.name, trackCount: playlist.trackIds.length, author: "You" }); saveState(); render(); }
function showView(viewName) { document.querySelectorAll(".view").forEach((view) => view.classList.toggle("active-view", view.id === `${viewName}View`)); document.querySelectorAll(".nav-link").forEach((link) => link.classList.toggle("active", link.dataset.view === viewName)); document.getElementById("viewLabel").textContent = viewName[0].toUpperCase() + viewName.slice(1); }

elements.songInput.addEventListener("change", () => addSongs([...elements.songInput.files])); elements.search.addEventListener("input", renderTracks); elements.play.addEventListener("click", () => { if (!currentTrackId) moveTrack(1); else if (elements.audio.paused) elements.audio.play(); else elements.audio.pause(); updatePlayButton(); }); document.getElementById("previousButton").addEventListener("click", () => moveTrack(-1)); document.getElementById("nextButton").addEventListener("click", () => moveTrack(1)); document.getElementById("loopButton").addEventListener("click", (event) => { elements.audio.loop = !elements.audio.loop; event.currentTarget.classList.toggle("loop-active", elements.audio.loop); event.currentTarget.setAttribute("aria-pressed", String(elements.audio.loop)); }); elements.volume.addEventListener("input", () => { elements.audio.volume = elements.volume.value; }); elements.progress.addEventListener("input", () => { if (elements.audio.duration) elements.audio.currentTime = (elements.progress.value / 100) * elements.audio.duration; }); elements.audio.addEventListener("loadedmetadata", () => { elements.duration.textContent = formatTime(elements.audio.duration); }); elements.audio.addEventListener("timeupdate", () => { elements.currentTime.textContent = formatTime(elements.audio.currentTime); elements.progress.value = elements.audio.duration ? (elements.audio.currentTime / elements.audio.duration) * 100 : 0; }); elements.audio.addEventListener("ended", () => { if (!elements.audio.loop) moveTrack(1); });
document.querySelectorAll(".nav-link").forEach((link) => link.addEventListener("click", (event) => { event.preventDefault(); if (link.dataset.view === "library") selectLibrary(); else showView(link.dataset.view); })); document.getElementById("newPlaylistButton").addEventListener("click", createPlaylist); document.getElementById("newPlaylistButtonMain").addEventListener("click", createPlaylist); document.getElementById("publishButton").addEventListener("click", publishPlaylist);
document.getElementById("exportButton").addEventListener("click", () => { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "bluenote-library.json"; link.click(); URL.revokeObjectURL(link.href); }); document.getElementById("importInput").addEventListener("change", async (event) => { const file = event.target.files[0]; if (!file) return; try { const imported = JSON.parse(await file.text()); if (!imported.tracks || !imported.playlists) throw new Error("Invalid library"); Object.assign(state, imported); saveState(); render(); } catch { alert("That file is not a valid BlueNote library export."); } event.target.value = ""; });
elements.exportButton.addEventListener("click", exportPlaylistArchive);
elements.importArchiveInput.addEventListener("change", importPlaylistArchive);
elements.archiveButton.addEventListener("click", () => { if (typeof elements.archiveDialog.showModal === "function") elements.archiveDialog.showModal(); else elements.archiveDialog.setAttribute("open", ""); });
elements.closeArchiveButton.addEventListener("click", () => { if (typeof elements.archiveDialog.close === "function") elements.archiveDialog.close(); else elements.archiveDialog.removeAttribute("open"); });
document.getElementById("unlockForm").addEventListener("submit", async (event) => { event.preventDefault(); const message = document.getElementById("unlockMessage"); message.textContent = "Checking the three keys..."; try { unlockKey = await verifyUnlock([document.getElementById("passwordOne").value, document.getElementById("passwordTwo").value, document.getElementById("passwordThree").value]); if (!unlockKey) throw new Error("Invalid keys"); document.body.classList.add("is-unlocked"); elements.audio.volume = elements.volume.value; render(); message.textContent = ""; } catch { unlockKey = null; message.textContent = "Those keys did not open the cave."; } });

